Created fixtures for MenuItemReview
ucsb-cs156-f23/team03-f23-6pm-3 pull request #71
Opened 2023-11-04 05:12 UTC by bella-ward

Created fixtures for MenuItemReview. 

Closes #36

2023-11-06 04:11 UTC, YicongYan requested changes
line 11 in menuItemReviewFixtures.js should be changed to "threeItemReviews"

2023-11-06 04:11 UTC, YicongYan commented on frontend/src/fixtures/menuItemReviewFixtures.js
> +    threeDates: [
should be changed to "threeItemReviews"

2023-11-06 04:40 UTC, bella-ward commented on frontend/src/fixtures/menuItemReviewFixtures.js
> +    threeDates: [
Ahh, thanks  changed it.

2023-11-06 21:15 UTC, YicongYan approved these changes
Looks good to me now!

2023-11-06 21:50 UTC, YicongYan requested changes
OK, the Fixture looks good to me, but it seems like you also contain a MenuitemItemForm.js without a test, and that causes some test fails on Github. I also noticed that some new lines are added to package-lock.json, so it seems dangerous to me to merge it. I will need to talk with a few other team members about it. **But please don't worry about it, because I'm still not sure whether it's a problem. If it is, we will fix it as a team. it's not going to be a big problem, so plz plz don't worry**

2023-11-08 22:47 UTC, merged

2023-11-08 22:47 UTC, YicongYan commented
Looks good to me!